title: ControllerBuddy
description: Highly advanced game controller mapping
baseurl: ""
url: https://controllerbuddy.org
twitter_username: bwRavencl
github_username:  bwRavencl

author:
  name: Matteo Hausner
  url: https://bwravencl.de

logo: https://github.com/bwRavencl/ControllerBuddy/raw/master/icon.svg

theme: jekyll-theme-cayman

permalink: news/:title

plugins:
  - jekyll-feed
